version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: scope
    labels: [ dependencies, automerge ]
    groups:
      gradle-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "ci"
      include: scope
    labels: [ ci, automerge ]
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
