name: AutoPost LLM Scheduler
on:
  schedule:
    - cron: "5 0 * * *"   # 00:05 daily (UTC) - adjust for London time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: "17"
      
      - name: Build
        run: mvn -q -DskipTests package
      
      - name: Write service account file
        run: echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > sa.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      
      - name: Run Application
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          RAW_FOLDER_ID: ${{ secrets.RAW_FOLDER_ID }}
          EDITS_FOLDER_ID: ${{ secrets.EDITS_FOLDER_ID }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          java -jar target/autopost.jar &
          APP_PID=$!
          sleep 300  # Run for 5 minutes to allow scheduling
          kill $APP_PID || true
      
      - name: Commit state files
        run: |
          git config user.name "autopost-bot"
          git config user.email "autopost-bot@users.noreply.github.com"
          git add -A state/
          git commit -m "chore: update posting schedule" || echo "No changes"
          git push