name: Ship Bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  ship:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ship')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR
        id: pr
        uses: actions-ecosystem/action-get-issue-related-prs@v1

      - name: Add automerge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pr_numbers }}
          merge-method: SQUASH