name: AutoPost & Analyze

on:
  schedule:
    - cron: "0 * * * *"   # Hourly; internal gating decides real execution times
  workflow_dispatch:
    inputs:
      mode:
        description: "run | analyze | both"
        required: false
        default: "run"
      dry_run:
        description: "true to avoid external posting (simulation)"
        required: false
        default: "false"
      force:
        description: "true to bypass time gating"
        required: false
        default: "false"
  # External event triggers (e.g. via curl / API)
  repository_dispatch:
    types: [autopost_run, autopost_analyze]

permissions:
  contents: write

# Prevent overlapping runs of this workflow (analysis + autopost share a group)
concurrency:
  group: autopost
  cancel-in-progress: false

env:
  CLIP_DURATION_SEC: "20"
  TEASER_DURATION_SEC: "180"
  NUM_CLIPS: "3"
  SCENE_THRESHOLD: "0.4"

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Weekly analysis (best posting times)
    steps:
      - name: Decide if analysis should run
        id: gate
        run: |
          set -euo pipefail
          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          MODE_INPUT="${{ github.event.inputs.mode || 'run' }}"
          FORCE_INPUT="${{ github.event.inputs.force || 'false' }}"
          # repository_dispatch client_payload (may be empty for other events)
          PAYLOAD_FORCE="${{ github.event.client_payload.force }}"
          PAYLOAD_MODE="${{ github.event.client_payload.mode }}"

          # Map repository_dispatch type -> initial mode
          if [ "$EVENT" = "repository_dispatch" ]; then
            if [ "$ACTION" = "autopost_analyze" ]; then MODE_INPUT="analyze"; fi
            if [ "$ACTION" = "autopost_run" ]; then MODE_INPUT="run"; fi
            [ -n "${PAYLOAD_MODE}" ] && MODE_INPUT="${PAYLOAD_MODE}"
            [ -n "${PAYLOAD_FORCE}" ] && FORCE_INPUT="${PAYLOAD_FORCE}"
          fi

          DOW=$(date -u +%u)   # 1=Mon
          HM=$(date -u +%H:%M)
          SHOULD="false"

          # Allow analysis if:
          # * forced
          # * mode explicitly analyze or both
          # * scheduled weekly slot Monday 03:00 UTC
          if [ "$FORCE_INPUT" = "true" ]; then SHOULD="true"; fi
            if [ "$MODE_INPUT" = "analyze" ] || [ "$MODE_INPUT" = "both" ]; then SHOULD="true"; fi
          if [ "$DOW" = "1" ] && [ "$HM" = "03:00" ]; then SHOULD="true"; fi

          echo "mode=$MODE_INPUT" >> "$GITHUB_OUTPUT"
          echo "should_run=$SHOULD" >> "$GITHUB_OUTPUT"
          echo "Resolved EVENT=$EVENT ACTION=$ACTION MODE=$MODE_INPUT FORCE=$FORCE_INPUT (UTC now $(date -u))"
      - if: steps.gate.outputs.should_run == 'true'
        uses: actions/checkout@v4
      - if: steps.gate.outputs.should_run == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - if: steps.gate.outputs.should_run == 'true'
        name: Build (skip tests)
        run: mvn -q -DskipTests package
      - if: steps.gate.outputs.should_run == 'true'
        name: Run analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RAW_FOLDER_ID: "unused"
          EDITS_FOLDER_ID: "unused"
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          set -euo pipefail
          java -jar target/autopost.jar analyze
      - if: steps.gate.outputs.should_run == 'true'
        name: Commit updated analysis artifacts
        run: |
          set -euo pipefail
          git config user.name "autopost-bot"
          git config user.email "autopost-bot@users.noreply.github.com"
          for f in best_slots.json analysis.md; do
            [ -f "$f" ] && git add "$f"
          done
          if git diff --cached --quiet; then
            echo "No analysis changes to commit."
          else
            current_branch="${GITHUB_REF_NAME:-main}"
            git commit -m "chore: update best posting slots"
            git pull --rebase origin "$current_branch" || true
            git push
          fi
      - if: steps.gate.outputs.should_run == 'true'
        name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
            name: analysis-artifacts
            path: |
              best_slots.json
              analysis.md
            if-no-files-found: ignore
      - name: Summary (analysis)
        if: always()
        run: |
          {
            echo "### Analysis Job"
            echo "* Ran: ${{ steps.gate.outputs.should_run }}"
            echo "* Mode: ${{ steps.gate.outputs.mode }}"
            echo "* Status: ${{ job.status }}"
            echo "* Time (UTC): $(date -u)"
          } >> "$GITHUB_STEP_SUMMARY"

  autopost:
    runs-on: ubuntu-latest
    name: Daily AutoPost
    needs: [analyze]
    steps:
      - name: Decide if posting should run
        id: gate
        run: |
          set -euo pipefail
          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          MODE_INPUT="${{ github.event.inputs.mode || 'run' }}"
          FORCE_INPUT="${{ github.event.inputs.force || 'false' }}"
          DRY_INPUT="${{ github.event.inputs.dry_run || 'false' }}"
          PAYLOAD_FORCE="${{ github.event.client_payload.force }}"
          PAYLOAD_MODE="${{ github.event.client_payload.mode }}"
          PAYLOAD_DRY="${{ github.event.client_payload.dry_run }}"

          if [ "$EVENT" = "repository_dispatch" ]; then
            if [ "$ACTION" = "autopost_run" ]; then MODE_INPUT="run"; fi
            if [ "$ACTION" = "autopost_analyze" ]; then MODE_INPUT="analyze"; fi
            [ -n "$PAYLOAD_MODE" ] && MODE_INPUT="$PAYLOAD_MODE"
            [ -n "$PAYLOAD_FORCE" ] && FORCE_INPUT="$PAYLOAD_FORCE"
            [ -n "$PAYLOAD_DRY" ] && DRY_INPUT="$PAYLOAD_DRY"
          fi

          HM=$(date -u +%H:%M)
          TARGET="08:00" # Primary posting time (UTC)
          SHOULD="false"

          if [ "$FORCE_INPUT" = "true" ]; then
            SHOULD="true"
          elif [ "$MODE_INPUT" = "run" ] || [ "$MODE_INPUT" = "both" ]; then
            if [ "$HM" = "$TARGET" ]; then SHOULD="true"; fi
          fi

          echo "should_run=$SHOULD" >> "$GITHUB_OUTPUT"
          echo "dry_run=$DRY_INPUT" >> "$GITHUB_OUTPUT"
          echo "mode=$MODE_INPUT" >> "$GITHUB_OUTPUT"
          echo "Resolved EVENT=$EVENT ACTION=$ACTION MODE=$MODE_INPUT FORCE=$FORCE_INPUT DRY=$DRY_INPUT (UTC now $(date -u))"
      - if: steps.gate.outputs.should_run == 'true'
        uses: actions/checkout@v4
      - if: steps.gate.outputs.should_run == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - if: steps.gate.outputs.should_run == 'true'
        name: Install ffmpeg
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - if: steps.gate.outputs.should_run == 'true'
        name: Build (skip tests)
        run: mvn -q -DskipTests package
      - if: steps.gate.outputs.should_run == 'true'
        name: Write service account file
        run: printf '%s' "$GOOGLE_SERVICE_ACCOUNT_JSON" > sa.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      - if: steps.gate.outputs.should_run == 'true'
        name: Run autopost
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          RAW_FOLDER_ID: ${{ secrets.RAW_FOLDER_ID }}
          EDITS_FOLDER_ID: ${{ secrets.EDITS_FOLDER_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          CLIP_DURATION_SEC: ${{ env.CLIP_DURATION_SEC }}
          TEASER_DURATION_SEC: ${{ env.TEASER_DURATION_SEC }}
          NUM_CLIPS: ${{ env.NUM_CLIPS }}
          SCENE_THRESHOLD: ${{ env.SCENE_THRESHOLD }}
          DRY_RUN: ${{ steps.gate.outputs.dry_run }}
        run: |
          set -euo pipefail
          if [ "${DRY_RUN}" = "true" ]; then
            echo "DRY RUN: Application should not post externally."
          fi
          java -jar target/autopost.jar run
      - if: steps.gate.outputs.should_run == 'true'
        name: Cleanup
        run: rm -f sa.json
      - name: Upload autopost artifacts
        if: steps.gate.outputs.should_run == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: autopost-output
          path: |
            best_slots.json
            analysis.md
          if-no-files-found: ignore
      - name: Summary (autopost)
        if: always()
        run: |
          {
            echo "### Autopost Job"
            echo "* Ran: ${{ steps.gate.outputs.should_run }}"
            echo "* Mode: ${{ steps.gate.outputs.mode }}"
            echo "* Status: ${{ job.status }}"
            echo "* Dry run: ${{ steps.gate.outputs.dry_run }}"
            echo "* Time (UTC): $(date -u)"
          } >> "$GITHUB_STEP_SUMMARY"
