name: AutoPost (hourly gated)
on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - name: Build
        run: mvn -q -DskipTests package
      - name: Write service account file
        run: echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > sa.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      - name: Run (gated)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          RAW_FOLDER_ID: ${{ secrets.RAW_FOLDER_ID }}
          EDITS_FOLDER_ID: ${{ secrets.EDITS_FOLDER_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          CLIP_DURATION_SEC: "20"
          TEASER_DURATION_SEC: "180"
          NUM_CLIPS: "3"
          SCENE_THRESHOLD: "0.4"
        run: java -jar target/autopost.jar run
