name: Build & Publish (Gradle + GH Packages)

on:
  push:
    branches: [ main ]
    tags: ["v*"]    # e.g. v1.0.0
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_PUBLIC_ID: ${{ secrets.SERVICE_PUBLIC_ID }}
      SERVICE_SECRET_KEY: ${{ secrets.SERVICE_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Build (unit + integration tests)
        run: gradle build --no-daemon

      - name: Publish to GitHub Packages
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: gradle publish --no-daemon
