name: Build & Publish (Maven + GH Packages)

on:
  push:
    branches: [ main ]
    tags: ["v*"]          # e.g. v1.0.0
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: >-
        -Djava.net.preferIPv4Stack=true
        -Dmaven.wagon.http.retryHandler.count=10
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
        -Dhttp.keepAlive=false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 + Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Write Maven settings (mirror + timeouts)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <!-- Force central to official endpoint to avoid flaky DNS -->
              <mirror>
                <id>central-mirror</id>
                <name>Maven Central (Mirror)</name>
                <url>https://repo.maven.apache.org/maven2</url>
                <mirrorOf>central</mirrorOf>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>ci-wagon</id>
                <properties>
                  <maven.wagon.http.retryHandler.count>10</maven.wagon.http.retryHandler.count>
                  <maven.wagon.http.pool>false</maven.wagon.http.pool>
                  <maven.wagon.httpconnectionManager.ttlSeconds>25</maven.wagon.httpconnectionManager.ttlSeconds>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>ci-wagon</activeProfile>
            </activeProfiles>
          </settings>
          XML

      - name: Build & Test
        run: mvn -B -U -q clean test -Djava.net.preferIPv4Stack=true

      - name: Package (non-PR)
        if: ${{ github.event_name != 'pull_request' }}
        run: mvn -B -U -q -DskipTests package -Djava.net.preferIPv4Stack=true

      - name: Set version from tag (vX.Y.Z)
        if: startsWith(github.ref, 'refs/tags/v')
        run: mvn -B -q versions:set -DnewVersion="${GITHUB_REF_NAME#v}" -DgenerateBackupPoms=false

      - name: Deploy to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -U -q -DskipTests deploy -Djava.net.preferIPv4Stack=true
