name: Build & Publish (Maven + GitHub Packages)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # needed to publish to GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # --- Create ~/.m2/settings.xml with auth for GitHub Packages + Maven Central
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <!-- MUST match the <id> used in your pom's distributionManagement/repositories -->
              <server>
                <id>github</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>

            <!-- Optional: define a mirror for Maven Central (explicit URL avoids DNS hiccups) -->
            <mirrors>
              <mirror>
                <id>central</id>
                <name>Maven Central</name>
                <url>https://repo1.maven.org/maven2/</url>
                <mirrorOf>central</mirrorOf>
              </mirror>
            </mirrors>

            <!-- If you use a corporate/proxy, uncomment and set host/port
            <proxies>
              <proxy>
                <active>true</active>
                <protocol>https</protocol>
                <host>proxy.example.com</host>
                <port>8080</port>
                <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
              </proxy>
            </proxies>
            -->
          </settings>
          XML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Build & Test
        run: mvn -B -q -U clean test

      # Publish only on tags (or keep on every push if you want)
      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B -q -U deploy -DskipTests
