name: Setup & Build AutoPost
on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set JAVA 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build (Maven, skip tests)
        run: mvn -B -DskipTests package

      - name: Verify artifact exists
        run: |
          ls -lh target || true
          test -f target/autopost.jar

      - name: Attest build provenance
        if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ github.workspace }}/target/autopost.jar
