name: Setup & Build AutoPost
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set AUTO_POST_CRON
        run: echo "AUTO_POST_CRON=${AUTO_POST_CRON:-0 5 0 * * *}" >> $GITHUB_ENV

      - name: Run setup script
        run: bash scripts/setup-everything.sh
