name: Setup AutoPost (one-shot)
on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if setup already completed
        id: check_setup
        run: |
          if [ -f "src/main/java/com/autopost/App.java" ] && [ -f ".github/workflows/autopost-hourly.yml" ]; then
            echo "Setup already completed - files exist"
            echo "setup_complete=true" >> $GITHUB_OUTPUT
          else
            echo "Setup needed - files missing"
            echo "setup_complete=false" >> $GITHUB_OUTPUT
          fi

      - name: Write project from archive
        if: steps.check_setup.outputs.setup_complete == 'false'
        run: |
          set -euo pipefail
          rm -f create-java.sh .github/workflows/scaffold.yml || true
          rm -rf src || true
          unzip -o files.zip

      - name: Commit & push
        if: steps.check_setup.outputs.setup_complete == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "autopost-bot"
          git config user.email "autopost-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit - setup already complete"
            exit 0
          else
            git commit -m "setup: one-shot scaffold; remove old helpers"
            git push
          fi
